const LANGS = {
  ru: {
    // Sidebar nav groups
    searchContent: 'Поиск контента',
    home: 'Главная',
    searchByWord: 'Поиск по слову',
    spy: 'Шпионаж',
    contentRadar: 'Контент-радар',
    socialMedia: 'Работа с соцсетями',
    crossPosting: 'Кросс-постинг',
    carousels: 'Карусели',
    tools: 'Инструменты',
    aiScript: 'AI-сценарий',
    newCarousel: 'Карусели',
    videoAnalysis: 'Анализ видео',
    profileAnalysis: 'Анализ профиля',
    drafts: 'Черновик',
    contentPlan: 'Контент план',
    ideas: 'Идеи',
    favorites: 'Избранные',
    history: 'История',
    bookmarks: 'Закладки',
    more: 'Ещё',
    training: 'Обучение',
    referrals: 'Рефералы',
    suggestIdea: 'Предложить идею',
    support: 'Поддержка',
    soon: 'Скоро',
    tokens: 'Токены',
    signOut: 'Выйти',
    creativePlus: 'Creative +',
    // Dashboard
    dashCreateTitle: 'Создайте карусель',
    dashCreateDesc: 'Вставьте контент, ИИ сгенерирует слайды, затем оформите и экспортируйте в Instagram.',
    dashAdd: 'Добавить',
    dashTotal: 'всего',
    dashReady: 'готовых',
    dashDraft: 'черновиков',
    // Login
    loginWelcome: 'Добро пожаловать',
    loginSubtitle: 'Войдите в trendsee',
    loginUsername: 'Имя пользователя',
    loginPassword: 'Пароль',
    loginButton: 'Войти',
    loginLoading: 'Вход…',
    loginNoAccount: 'Нет аккаунта?',
    loginCreateOne: 'Создать',
    loginErrorWrong: 'Неверное имя пользователя или пароль',
    loginErrorFail: 'Ошибка входа. Попробуйте снова.',
    // Register
    registerTitle: 'Создайте аккаунт',
    registerSubtitle: 'Начните работу с trendsee',
    registerUsername: 'Имя пользователя',
    registerUsernameHint: '3–32 символа: буквы, цифры, подчёркивания',
    registerPassword: 'Пароль',
    registerPasswordHint: 'Минимум 6 символов',
    registerConfirm: 'Подтвердите пароль',
    registerButton: 'Создать аккаунт',
    registerLoading: 'Создание…',
    registerHaveAccount: 'Уже есть аккаунт?',
    registerSignIn: 'Войти',
    registerErrorMismatch: 'Пароли не совпадают',
    registerErrorTaken: 'Имя занято. Выберите другое.',
    registerErrorFail: 'Ошибка регистрации. Попробуйте снова.',
    // Profile
    profileTitle: 'Профиль',
    profileMemberSince: 'Участник с',
    profileUsername: 'Имя пользователя',
    profileAccountId: 'ID аккаунта',
    profileUsage: 'Использование',
    profileCarousels: 'каруселей',
    profileGenerations: 'генераций',
    profileTokensUsed: 'токенов',
    profileChangePw: 'Сменить пароль',
    profileCurrentPw: 'Текущий пароль',
    profileNewPw: 'Новый пароль',
    profileConfirmPw: 'Подтвердите новый пароль',
    profileSaving: 'Сохранение…',
    profileSaveBtn: 'Сменить пароль',
    profilePwSuccess: 'Пароль успешно изменён.',
    profilePwErrorWrong: 'Текущий пароль неверен',
    profilePwErrorFail: 'Не удалось сменить пароль. Попробуйте снова.',
    profilePwErrorMismatch: 'Новые пароли не совпадают',
    profileSignOut: 'Выйти',
    profileSignOutDesc: 'Для доступа к каруселям нужно будет войти снова.',
    profileSignOutBtn: 'Выйти из аккаунта',
    // New carousel / editor
    navCarousels: 'Карусели',
    navNewCarousel: 'Новая карусель',
    navMyContext: 'Мой контекст',
    navCreate: 'Создать',
    chooseMethod: 'Выберите способ создания',
    srcText: 'Свой текст',
    srcVideo: 'Создать из видео',
    srcLinks: 'Создать из карусели',
    srcPlaceholder: 'Выберите способ создания карусели',
    srcVideoNotes: 'Заметки (необязательно)',
    srcAddLink: '+ Добавить ссылку',
    slidesLabel: (n: number) => `${n} слайдов`,
    generateBtn: 'Генерировать',
    generatingBtn: 'Генерируем…',
    sourceTextBtn: 'Исходный текст',
    generatingSlides: 'Генерируем слайды с помощью ИИ…',
    previewHint: 'Предпросмотр карусели. Нажмите "В редактор" для редактирования',
    redoBtn: 'Переделать',
    toEditorBtn: 'В редактор',
    exportBtn: 'Экспорт',
    tabTemplate: 'Шаблон',
    tabBackground: 'Фон',
    tabTypography: 'Текст',
    tabLayout: 'Макет',
    tabExtra: 'Дополнительно',
    exportReady: 'Готовые изображения',
    recreateBtn: 'Пересоздать',
    backToEditor: 'Назад в редактор',
    downloadSlide: 'Скачать',
    downloadAll: 'Скачать все',
    slidesSuccess: (n: number) => `Все ${n} ${n === 1 ? 'слайд успешно создан' : n < 5 ? 'слайда успешно созданы' : 'слайдов успешно созданы'}!`,
    generationFailed: 'Генерация не удалась. Попробуйте снова.',
  },
  en: {
    // Sidebar nav groups
    searchContent: 'Content Search',
    home: 'Home',
    searchByWord: 'Search by word',
    spy: 'Spy',
    contentRadar: 'Content Radar',
    socialMedia: 'Social Media',
    crossPosting: 'Cross-posting',
    carousels: 'Carousels',
    tools: 'Tools',
    aiScript: 'AI Script',
    newCarousel: 'Carousels',
    videoAnalysis: 'Video Analysis',
    profileAnalysis: 'Profile Analysis',
    drafts: 'Drafts',
    contentPlan: 'Content Plan',
    ideas: 'Ideas',
    favorites: 'Favorites',
    history: 'History',
    bookmarks: 'Bookmarks',
    more: 'More',
    training: 'Training',
    referrals: 'Referrals',
    suggestIdea: 'Suggest idea',
    support: 'Support',
    soon: 'Soon',
    tokens: 'Tokens',
    signOut: 'Sign out',
    creativePlus: 'Creative +',
    // Dashboard
    dashCreateTitle: 'Create a carousel',
    dashCreateDesc: 'Paste content, let AI generate slides, then style and export as Instagram-ready images.',
    dashAdd: 'Add',
    dashTotal: 'total',
    dashReady: 'ready',
    dashDraft: 'draft',
    // Login
    loginWelcome: 'Welcome back',
    loginSubtitle: 'Sign in to trendsee',
    loginUsername: 'Username',
    loginPassword: 'Password',
    loginButton: 'Sign in',
    loginLoading: 'Signing in…',
    loginNoAccount: "Don't have an account?",
    loginCreateOne: 'Create one',
    loginErrorWrong: 'Incorrect username or password',
    loginErrorFail: 'Sign in failed. Please try again.',
    // Register
    registerTitle: 'Create your account',
    registerSubtitle: 'Get started with trendsee',
    registerUsername: 'Username',
    registerUsernameHint: '3–32 characters, letters, numbers, underscores',
    registerPassword: 'Password',
    registerPasswordHint: 'Minimum 6 characters',
    registerConfirm: 'Confirm Password',
    registerButton: 'Create account',
    registerLoading: 'Creating account…',
    registerHaveAccount: 'Already have an account?',
    registerSignIn: 'Sign in',
    registerErrorMismatch: 'Passwords do not match',
    registerErrorTaken: 'Username already taken. Please choose another.',
    registerErrorFail: 'Registration failed. Please try again.',
    // Profile
    profileTitle: 'Profile',
    profileMemberSince: 'Member since',
    profileUsername: 'Username',
    profileAccountId: 'Account ID',
    profileUsage: 'Usage',
    profileCarousels: 'carousels',
    profileGenerations: 'generations',
    profileTokensUsed: 'tokens used',
    profileChangePw: 'Change Password',
    profileCurrentPw: 'Current Password',
    profileNewPw: 'New Password',
    profileConfirmPw: 'Confirm New Password',
    profileSaving: 'Saving…',
    profileSaveBtn: 'Change Password',
    profilePwSuccess: 'Password changed successfully.',
    profilePwErrorWrong: 'Current password is incorrect',
    profilePwErrorFail: 'Failed to change password. Please try again.',
    profilePwErrorMismatch: 'New passwords do not match',
    profileSignOut: 'Sign Out',
    profileSignOutDesc: "You'll need to sign back in to access your carousels.",
    profileSignOutBtn: 'Sign out',
    // New carousel / editor
    navCarousels: 'Carousels',
    navNewCarousel: 'New carousel',
    navMyContext: 'My Context',
    navCreate: 'Create',
    chooseMethod: 'Choose creation method',
    srcText: 'My text',
    srcVideo: 'Create from video',
    srcLinks: 'Create from carousel',
    srcPlaceholder: 'Choose how to create your carousel',
    srcVideoNotes: 'Notes (optional)',
    srcAddLink: '+ Add link',
    slidesLabel: (n: number) => `${n} slides`,
    generateBtn: 'Generate',
    generatingBtn: 'Generating…',
    sourceTextBtn: 'Source text',
    generatingSlides: 'Generating slides with AI…',
    previewHint: 'Carousel preview. Click "To editor" to edit',
    redoBtn: 'Redo',
    toEditorBtn: 'To editor',
    exportBtn: 'Export',
    tabTemplate: 'Template',
    tabBackground: 'Background',
    tabTypography: 'Text',
    tabLayout: 'Layout',
    tabExtra: 'Extra',
    exportReady: 'Ready images',
    recreateBtn: 'Recreate',
    backToEditor: 'Back to editor',
    downloadSlide: 'Download',
    downloadAll: 'Download all',
    slidesSuccess: (n: number) => `All ${n} ${n === 1 ? 'slide created' : 'slides created'} successfully!`,
    generationFailed: 'Generation failed. Please try again.',
  },
}

type Lang = 'ru' | 'en'

const lang = ref<Lang>(
  import.meta.client ? ((localStorage.getItem('lang') as Lang) ?? 'ru') : 'ru'
)

export function useLang() {
  const t = computed(() => LANGS[lang.value])

  const setLang = (l: Lang) => {
    lang.value = l
    if (import.meta.client) localStorage.setItem('lang', l)
  }

  const toggleLang = () => setLang(lang.value === 'ru' ? 'en' : 'ru')

  return { lang: readonly(lang), t, setLang, toggleLang }
}
