<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition-opacity duration-200"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition-opacity duration-150"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div v-if="visible" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
        <div class="bg-white rounded-2xl shadow-2xl w-full max-w-sm overflow-hidden">

          <!-- Steps -->
          <div class="relative overflow-hidden">
            <div class="flex transition-transform duration-300 ease-out"
              :style="{ transform: `translateX(-${step * 100}%)` }">

              <!-- Step 1 -->
              <div class="w-full shrink-0 px-7 pt-8 pb-6">
                <div class="flex items-center gap-2 mb-5">
                  <img src="/visible.png" alt="trendsee" class="w-9 h-9 object-contain" />
                  <span class="font-semibold text-[#1B1A25]" style="font-family:'Unbounded',sans-serif;font-size:18px;line-height:1.2;">trendsee</span>
                </div>
                <h2 class="text-lg font-bold text-[#1c1c1e] mb-2">Welcome to trendsee</h2>
                <p class="text-sm text-[#3a3a3c] leading-relaxed">
                  Turn any article, video, or set of links into Instagram carousel slides — generated by AI in seconds.
                </p>
              </div>

              <!-- Step 2 -->
              <div class="w-full shrink-0 px-7 pt-8 pb-6">
                <div class="w-11 h-11 bg-[#34c759]/10 rounded-2xl flex items-center justify-center mb-5">
                  <svg class="w-5 h-5 text-[#34c759]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                </div>
                <h2 class="text-lg font-bold text-[#1c1c1e] mb-2">Add your content</h2>
                <p class="text-sm text-[#3a3a3c] leading-relaxed mb-4">
                  Choose a source and let AI do the writing. Pick language, slide count, and tone.
                </p>
                <div class="space-y-2">
                  <div v-for="item in step2Items" :key="item.label"
                    class="flex items-center gap-3 py-2 border-b border-[#f2f2f7] last:border-0">
                    <div class="w-7 h-7 rounded-lg bg-[#f2f2f7] flex items-center justify-center shrink-0">
                      <svg class="w-3.5 h-3.5 text-[#3a3a3c]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="item.icon" />
                      </svg>
                    </div>
                    <div>
                      <p class="text-xs font-semibold text-[#1c1c1e]">{{ item.label }}</p>
                      <p class="text-xs text-[#8e8e93]">{{ item.desc }}</p>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Step 3 -->
              <div class="w-full shrink-0 px-7 pt-8 pb-6">
                <div class="w-11 h-11 bg-purple-100 rounded-2xl flex items-center justify-center mb-5">
                  <svg class="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                </div>
                <h2 class="text-lg font-bold text-[#1c1c1e] mb-2">Design &amp; export</h2>
                <p class="text-sm text-[#3a3a3c] leading-relaxed mb-4">
                  Edit text, pick a template, upload photos per slide. Export as a ZIP of 1080×1350 px PNGs, ready for Instagram.
                </p>
                <div class="space-y-2">
                  <div v-for="item in step3Items" :key="item.label"
                    class="flex items-center gap-3 py-2 border-b border-[#f2f2f7] last:border-0">
                    <div class="w-7 h-7 rounded-lg bg-[#f2f2f7] flex items-center justify-center shrink-0">
                      <svg class="w-3.5 h-3.5 text-[#3a3a3c]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="item.icon" />
                      </svg>
                    </div>
                    <div>
                      <p class="text-xs font-semibold text-[#1c1c1e]">{{ item.label }}</p>
                      <p class="text-xs text-[#8e8e93]">{{ item.desc }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Footer -->
          <div class="px-7 pb-7 flex items-center gap-3">
            <!-- Dots -->
            <div class="flex gap-1.5 flex-1">
              <button v-for="i in 3" :key="i"
                class="rounded-full transition-all duration-200"
                :class="step === i - 1 ? 'w-4 h-1.5 bg-[#0071e3]' : 'w-1.5 h-1.5 bg-[#d1d1d6]'"
                :aria-label="`Go to step ${i}`"
                @click="step = i - 1" />
            </div>
            <button v-if="step > 0" class="btn-secondary text-sm px-4 py-2" @click="step--">Back</button>
            <button v-if="step < 2" class="btn-primary text-sm px-4 py-2" @click="step++">Next</button>
            <button v-else class="btn-primary text-sm px-4 py-2" @click="dismiss">Get started</button>
          </div>

          <!-- Close -->
          <button
            class="absolute top-4 right-4 w-7 h-7 flex items-center justify-center rounded-full text-[#8e8e93] hover:bg-black/5 transition-colors"
            aria-label="Close welcome guide"
            @click="dismiss">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
const STORAGE_KEY = "carouselgen_onboarded"
const visible = ref(false)
const step = ref(0)

const step2Items = [
  { label: "From text", desc: "Paste an article or any draft copy.", icon: "M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" },
  { label: "From video", desc: "Paste a video URL with context notes.", icon: "M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" },
  { label: "From links", desc: "Curate URLs with bullet-point context.", icon: "M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" },
]

const step3Items = [
  { label: "7 templates", desc: "Global or per-slide — mix and match.", icon: "M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z" },
  { label: "Custom backgrounds", desc: "Upload a photo or pick a color per slide.", icon: "M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" },
  { label: "Export as ZIP", desc: "1080×1350 px PNG files, ready to post.", icon: "M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" },
]

const dismiss = () => {
  visible.value = false
  if (typeof localStorage !== "undefined") localStorage.setItem(STORAGE_KEY, "1")
}

onMounted(() => {
  if (typeof localStorage !== "undefined" && !localStorage.getItem(STORAGE_KEY)) {
    visible.value = true
  }
})
</script>
